image:
  name: hashicorp/terraform:1.3.2
  entrypoint:
  - "/usr/bin/env"
  - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

stages:
- deploy

deploy-job:
  stage: deploy
  before_script:
  - cp $GCP_KEY_FILE /tmp/credentials.json
  - export GOOGLE_APPLICATION_CREDENTIALS="/tmp/credentials.json"
  - terraform init
  script:
  - terraform apply -auto-approve -var="project_id=$GCP_PROJECT_ID" -var="region=us-central1" -var="image=gcr.io/$GCP_PROJECT_ID/serverless"
  after_script:
  - rm -f /tmp/gcloud-service-key.json
  only:
  - main
  - develop
