stages:          # List of stages for jobs, and their order of execution
  - deploy
 
deploy-job:     
  stage: deploy
  image: google/cloud-sdk:alpine
  script:
    - echo $GCP_KEY > /tmp/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yaml
    - echo "Application successfully deployed."
  only:
    - main
    - develop
 
after_script:
    - rm /tmp/gcloud-service-key.json